class RuleStuff;
class GroupItem;
class PLGset;
class Stak;
class Buffer;
/*******************************************************************************
	GroupRules
*******************************************************************************/

class GroupRules
{
public:
char *atRuleMark;
RuleStuff *ruleSTUFF;
GroupItem *currentMETHOD;
GroupItem *currentRegistry;
GroupItem *debugJunk;
GroupItem *baseRegistryList;
GroupItem *bcOPs;
GroupItem *commands;
GroupItem *files;
GroupItem *grokking;
GroupItem *groupFields;
GroupItem *keyWords;
GroupItem *opFields;
GroupItem *properties;
GroupItem *registries;
GroupItem *divertOutput;
GroupItem *falseResult;
GroupItem *inDENT;
GroupItem *lastREF;
GroupItem *lastStatement;
GroupItem *generator;
GroupItem *printSPACE;
GroupItem *ruleSkipSet;
GroupItem *runningActions;
GroupItem *searchList;
GroupItem *setupFILE;
GroupItem *sourceFILE;
GroupItem *tempField;
GroupItem *trueResult;
PLGset *alphaSet;
PLGset *nameSet;
PLGset *punctuateSet;
PLGset *shortcutSet;
PLGset *skipSet;
PLGset *spaceSet;
Stak *blockSTAK;
Stak *bufferSTAK;
Stak *inputSTAK;
int lastIndent;
int rulesParsed;
int sourceLINE;
char *beforeSkip;
char *lastSkip;
Buffer *fieldBUFFER;
Buffer *formatBUFFER;
Buffer *stringBUFFER;
Buffer *toBUFFER;
struct 
	{
	unsigned int debugAllRules:1;
	unsigned int debugGuards:1;
	unsigned int defining:1;
	unsigned int divertToRule:1;
	unsigned int endParse:1;
	unsigned int generating:1;
	unsigned int ignoreThis:1;
	unsigned int ignoreNoPrint:1;
	unsigned int ignoreNoRoom:1;
	unsigned int inputDiverted:1;
	unsigned int isPERCENT:1;
	unsigned int isPRINTING:1;
	unsigned int isRELATIVE:1;
	unsigned int isRigorous:1;
	unsigned int noSkipping:1;
	unsigned int processingCode:1;
	unsigned int showWarnings:1;
	unsigned int useDefaultSpace:1;
	unsigned int jitting:1;
	};
GroupRules();
char *checkSkip(char *atContent);
void popInput();
int pushInput(GroupItem *source);
};
extern "C" GroupItem *aCTionANYtoken(GroupItem *input);
extern "C" GroupItem *aCTionBlocK(GroupItem *input);
extern "C" GroupItem *aCTionBraced(GroupItem *input);
extern "C" GroupItem *aCTionBrancH(GroupItem *input);
extern "C" GroupItem *aCTionCheckFor(GroupItem *input);
extern "C" GroupItem *aCTionCodE(GroupItem *rule);
extern "C" GroupItem *aCTionDEBUG(GroupItem *input);
extern "C" GroupItem *aCTionDO(GroupItem *input);
extern "C" GroupItem *aCTionDefinE(GroupItem *input);
extern "C" GroupItem *aCTionExpressioN(GroupItem *xpList);
extern "C" GroupItem *aCTionFOR(GroupItem *input);
extern "C" GroupItem *aCTionFailed(GroupItem *input);
extern "C" GroupItem *aCTionIF(GroupItem *input);
extern "C" GroupItem *aCTionNamE(GroupItem *input);
extern "C" GroupItem *aCTionNumbeR(GroupItem *input);
extern "C" GroupItem *aCTionParens(GroupItem *input);
extern "C" GroupItem *aCTionPrinT(GroupItem *input);
extern "C" GroupItem *aCTionQuotE(GroupItem *input);
extern "C" GroupItem *aCTionRunRulE(GroupItem *input);
extern "C" void aCTionScopeXP(GroupItem *input);
extern "C" GroupItem *aCTionSearch(GroupItem *input);
extern "C" GroupItem *aCTionSetBrackets(GroupItem *group);
extern "C" GroupItem *aCTionShortcuT(GroupItem *group);
extern "C" GroupItem *aCTionStatemenT(GroupItem *input);
extern "C" GroupItem *aCTionTokenXP(GroupItem *xpress);
extern "C" GroupItem *aCTionTraiT(GroupItem *input);
extern "C" GroupItem *aCTionTraiTdata(GroupItem *input);
extern "C" GroupItem *aCTionWhilE(GroupItem *input);
extern "C" GroupItem *aCTionXpress(GroupItem *input);
extern "C" GroupItem *appendGroup(GroupItem *input, GroupItem *FormaT, Buffer *buffer);
extern "C" GroupItem *cLEAR(GroupItem *input);
extern "C" GroupItem *cOPY(GroupItem *field);
extern "C" int closeFile(GroupItem *bufField);
extern "C" GroupItem *concatEQ(GroupItem *target, GroupItem *argument);
extern "C" GroupItem *copyOf(GroupItem *grup);
extern "C" char *dataType(GroupItem *input);
extern "C" GroupItem *debugOnGuard(GroupItem *input);
extern "C" void debugRuleNamed(char *name);
extern "C" void debugText(GroupItem *debugStuff, int flag);
extern "C" void dispatcher(void *stuff);
extern "C" GroupItem *dumpContents(GroupItem *stuff);
extern "C" GroupItem *fAIL(GroupItem *input);
extern "C" void flushBuffer(GroupItem *bufField);
extern "C" GroupItem *generateCode(GroupItem *field);
extern "C" char *getDebugText(char *input, int length);
extern "C" GroupItem *getFile(GroupItem *filing);
extern "C" GroupItem *getMarkLineAt(GroupItem *argument);
extern "C" GroupItem *getType(GroupItem *field);
extern "C" GroupItem *guard(GroupItem *item);
extern "C" GroupItem *interpretBC(GroupItem *argument);
extern "C" GroupItem *interpretMethod(GroupItem *input);
extern "C" GroupItem *jitEmitAssign(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *jitEmitBinary(GroupItem *argument, GroupItem *target, int op);
extern "C" GroupItem *jitEmitCompare(GroupItem *argument, GroupItem *target, int op);
extern "C" GroupItem *jitEmitStringPlusEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *jitEmitUnary(GroupItem *target, int op);
extern "C" void *jitEngine();
extern "C" void jitForceInclude();
extern "C" void jitInitOnce();
extern "C" int jitRunAction(GroupItem *action);
extern "C" int jitRunAddTwo();
extern "C" GroupItem *jitSeedField(GroupItem *token);
extern "C" GroupItem *jitSeedLiteral(GroupItem *token);
extern "C" GroupItem *listenTo(GroupItem *input);
extern "C" GroupItem *loadDirectory(GroupItem *input);
extern "C" GroupItem *loadInputFromFile(GroupItem *source);
extern "C" void loadRegistryFromString(char *name, char *content);
extern "C" GroupItem *makeDataType(GroupItem *target, GroupItem *argument);
extern "C" GroupItem *makeNew(GroupItem *input);
extern "C" void modify(GroupItem *field, char *modifier);
extern "C" GroupItem *opAND(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opAddAttribute(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opAssign(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opCopyList(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opDebug(GroupItem *result);
extern "C" GroupItem *opDiv(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opDivEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opDot(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opEnd(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opGE(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opGT(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opGet(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opGetAttribute(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opGetMember(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opIN(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opLE(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opLT(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opLastREF(GroupItem *result);
extern "C" GroupItem *opMatch(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opMinus(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opMinusEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opMinusMinus(GroupItem *result);
extern "C" GroupItem *opMultiply(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opMultiplyEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opNOT(GroupItem *result);
extern "C" GroupItem *opNotEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opOR(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opPlus(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opPlusEQ(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opPlusPlus(GroupItem *result);
extern "C" GroupItem *opPointer(GroupItem *field);
extern "C" GroupItem *opPrint(GroupItem *target, Buffer *buffer);
extern "C" GroupItem *opRem(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opReplaceAttribute(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opReplaceMember(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opSetGroup(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opSetTag(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *opString(GroupItem *target, Buffer *buffer);
extern "C" void printField(GroupItem *field, char *format, Buffer *buffer);
extern "C" GroupItem *printToBuffer(GroupItem *bufferField);
extern "C" GroupItem *processAction(GroupItem *field);
extern "C" int processCode(GroupItem *field);
extern "C" GroupItem *processFlags(GroupItem *item);
extern "C" GroupItem *quoted(GroupItem *input);
extern "C" GroupItem *rEGISTER(GroupItem *item);
extern "C" GroupItem *resetField(GroupItem *argument);
extern "C" GroupItem *resolveList(GroupItem *input);
extern "C" void restoreLocalFields(GroupItem *action);
extern "C" GroupItem *ruleMethod(GroupItem *input);
extern "C" GroupItem *runAction(GroupItem *argument, GroupItem *field);
extern "C" GroupItem *runByteFn(GroupItem *instr);
extern "C" GroupItem *runOP(GroupItem *field);
extern "C" GroupItem *runRule(GroupItem *field, GroupItem *rule);
extern "C" GroupItem *runSystem(GroupItem *command);
extern "C" void saveLocalFields(GroupItem *action);
extern "C" int setCompiledMethod(GroupItem *block, char *name);
extern "C" void setFile(GroupItem *bufField, char *name);
extern "C" GroupItem *setFileOp(GroupItem *argument, GroupItem *target);
extern "C" GroupItem *setInternalType(GroupItem *grup);
extern "C" void setLimits(GroupItem *rule, GroupItem *limits);
extern "C" GroupItem *setMark(GroupItem *argument);
extern "C" GroupItem *setRuleAction(GroupItem *block);
extern "C" int statementMatches(GroupItem *a, GroupItem *b);
extern "C" GroupItem *stopParsingInput(GroupItem *input);
extern "C" GroupItem *testing(GroupItem *input);
extern "C" GroupItem *tokenize(GroupItem *label);
extern "C" void unMark(GroupItem *bufField);
extern "C" GroupItem *unWrap(GroupItem *result);
extern "C" char *wrapped(GroupItem *input);
extern "C" GroupItem *writeTempFile(GroupItem *bufField);
