class GroupItem;
class PLGitem;
class Buffer;
class PLGset;
class Stak;
class KeyTable;
/*****************************************************************************
	ParseXML class definition
*****************************************************************************/

class ParseXML : public PLGparse
{
public:
GroupItem *ancestor;
GroupItem *block;
GroupItem *currentBlock;
GroupItem *field;
GroupItem *fieldRegistry;
GroupItem *fileList;
GroupItem *foundItems;
GroupItem *jitInclude;
GroupItem *lastSelect;
GroupItem *list;
GroupItem *monthRegistry;
GroupItem *outerBlock;
GroupItem *record;
GroupItem *yearRegistry;
PLGitem *jitHeader;
PLGitem *testItem;
Buffer *scratch;
char *skip;
char *setName;
char delimiter;
char endRecord;
char outputDelimit;
char outputEnd;
int groupItems;
int openTags;
int recordNumber;
PLGset *notSpace;
PLGset *spaces;
Stak *blockStack;
Stak *endTags;
ParseXML *pathParser;
struct 
	{
	unsigned int jsonType:3;
	unsigned int complexPath:1;
	unsigned int doneWithHeading:1;
	unsigned int droppedAnchor:1;
	unsigned int firstTag:1;
	unsigned int hasHeading:1;
	unsigned int ignoreSkip:1;
	unsigned int isThreaded:1;
	unsigned int commanding:1;
	unsigned int noComments:1;
	unsigned int noLineByLine:1;
	unsigned int numberValues:1;
	unsigned int settingPath:1;
	unsigned int targetSet:1;
	unsigned int trimLeadingSpace:1;
	unsigned int useStash:1;
	};
#define isBlock(button) (button == 1)
#define isJSONtext(button) (button == 2)
#define isRepeat(button) (button == 3)
PLGset *alphaSet;
PLGset *anchorSet;
PLGset *bodySet;
PLGset *commentSet;
PLGset *dateSet;
PLGset *delimitSet;
PLGset *fieldSet;
PLGset *nameSet;
PLGset *singleQuote;
PLGset *tagSet;
PLGset *textSet;
KeyTable *Registering;
KeyTable *Flag;
KeyTable *CommandAction;
PLGset *simpleEnd;
PLGset *textFollow;
int simpleSyntax;
int stopParsing;
char *endString;
char *subString;
Stak *immediates;
ParseXML();
ParseXML(ParseXML *p);
void convertItem(PLGitem *item);
char *convertSetInput(PLGitem *item);
char *despace(char *s);
void filterBy(GroupItem *group, GroupItem *filter);
GroupItem *getFieldBlock(PLGitem *item);
int hasTarget(GroupItem *path);
void includeFile(char *filename);
void indentText(char *source, Buffer *buffer);
void initializeKeyWords();
void initializeSetTable();
PLGitem *isURL(char *text);
void listRegistries();
GroupItem *loadDelimited(GroupItem *specs);
void loadFieldSpecs(GroupItem *fieldSpecs);
GroupItem *loadJSON(GroupItem *specs);
GroupItem *loadRule(GroupItem *specs);
GroupItem *locate(PLGitem *item);
void makeShell();
GroupItem *parseFile(char *filename);
void parseMacro(GroupItem *macro, char *text);
char *parseStatements(char *code);
GroupItem *parseString(char *path, char *tag);
void popState();
void printAttributes(GroupItem *group, Stak *list);
void processDelimitField(PLGitem *item);
void processPath(GroupItem *item);
void processSourceByPath(GroupItem *path, GroupItem *item);
GroupItem *processTag(PLGitem *attributes);
void pushState();
void reset();
void resetItemTape();
PLGitem *run(char *name);
PLGitem *run(char *rule, char *text);
void searchListAdd(GroupItem *registry);
void setAncestry();
void setRules();
GroupItem *simplePath(GroupItem *item);
PLGitem *trimEnd(PLGitem *item);
};
int AttributeListParseXMLNow(PLGitem *iTEM);
void AttributeParseXMLAct(PLGitem *iTEM);
int BodyPartsParseXMLNow(PLGitem *iTEM);
void Closing2ParseXMLAct(PLGitem *iTEM);
void ClosingParseXMLAct(PLGitem *iTEM);
int CommandParseXMLNow(PLGitem *iTEM);
void CommandText2ParseXMLAct(PLGitem *iTEM);
void CommandText3ParseXMLAct(PLGitem *iTEM);
void CommandText4ParseXMLAct(PLGitem *iTEM);
void CommandText5ParseXMLAct(PLGitem *iTEM);
void CommandText6ParseXMLAct(PLGitem *iTEM);
void CommandText7ParseXMLAct(PLGitem *iTEM);
void CommandTextParseXMLAct(PLGitem *iTEM);
int DebuggingParseXMLNow(PLGitem *iTEM);
int DelimitEmptyParseXMLNow(PLGitem *iTEM);
int DelimitFieldNameParseXMLNow(PLGitem *iTEM);
void DelimitNumberParseXMLAct(PLGitem *iTEM);
void DelimitText2ParseXMLAct(PLGitem *iTEM);
void DelimitText3ParseXMLAct(PLGitem *iTEM);
void DelimitTextParseXMLAct(PLGitem *iTEM);
int EndBraceParseXMLNow(PLGitem *iTEM);
void EndTag2ParseXMLAct(PLGitem *iTEM);
int EndTag2ParseXMLNow(PLGitem *iTEM);
void EndTagParseXMLAct(PLGitem *iTEM);
int EndTagParseXMLNow(PLGitem *iTEM);
int FieldItemParseXMLNow(PLGitem *iTEM);
int FieldName3ParseXMLNow(PLGitem *iTEM);
int FieldName4ParseXMLNow(PLGitem *iTEM);
void JSONblockParseXMLAct(PLGitem *iTEM);
void JSONdata2ParseXMLAct(PLGitem *iTEM);
void JSONdata3ParseXMLAct(PLGitem *iTEM);
void JSONdataParseXMLAct(PLGitem *iTEM);
int JSONlistEntryParseXMLNow(PLGitem *iTEM);
void JSONpairParseXMLAct(PLGitem *iTEM);
void JSONrepeatEntryParseXMLAct(PLGitem *iTEM);
void JSONrepeatParseXMLAct(PLGitem *iTEM);
int LocateParseXMLNow(PLGitem *iTEM);
int MacroParseXMLNow(PLGitem *iTEM);
int MacroPartParseXMLNow(PLGitem *iTEM);
void ModifierParseXMLAct(PLGitem *iTEM);
int ModifierParseXMLNow(PLGitem *iTEM);
int NumberParseXMLNow(PLGitem *iTEM);
int PartParseXMLNow(PLGitem *iTEM);
void PathItemParseXMLAct(PLGitem *iTEM);
int PathParseXMLNow(PLGitem *iTEM);
int Quoted2ParseXMLNow(PLGitem *iTEM);
int QuotedParseXMLNow(PLGitem *iTEM);
int RegistryParseXMLNow(PLGitem *iTEM);
void SetAttributesParseXMLAct(PLGitem *iTEM);
int SetSimpleEndParseXMLNow(PLGitem *iTEM);
int SetTagFlagParseXMLNow(PLGitem *iTEM);
void SimpleEnd2ParseXMLAct(PLGitem *iTEM);
void SimpleEndParseXMLAct(PLGitem *iTEM);
int SkipGuardParseXMLNow(PLGitem *iTEM);
void StartTag2ParseXMLAct(PLGitem *iTEM);
void StartTagParseXMLAct(PLGitem *iTEM);
int StartXMLParseXMLNow(PLGitem *iTEM);
int StopHereParseXMLNow(PLGitem *iTEM);
int StringSetParseXMLNow(PLGitem *iTEM);
void Tag2ParseXMLAct(PLGitem *iTEM);
void Tag3ParseXMLAct(PLGitem *iTEM);
void TextBodyParseXMLAct(PLGitem *iTEM);
void UpParseXMLAct(PLGitem *iTEM);
